# Generated by Django 3.2.9 on 2023-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creater',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
